{{- if eq "azuredisk-retained" .Values.disk.storageclass -}}
# Copyright (C) 2019 GoVanguard Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
# 
# Portions of code based on code and concepts from 
# wazuh/wazuh-kubernetes Copyright (C) 2018 Wazuh Inc.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azuredisk-retained
provisioner: kubernetes.io/azure-disk
parameters:
  skuname: Standard_LRS
reclaimPolicy: Retain
{{- end }}
