# Copyright (C) 2019 GoVanguard Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
# 
# Portions of code based on code and concepts from 
# wazuh/wazuh-kubernetes Copyright (C) 2018 Wazuh Inc.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-worker-0
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: worker
      sts-id: '0'
  serviceName: wazuh-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: worker
        sts-id: '0'
      name: wazuh-manager-worker-0
      annotations:
        iam.amazonaws.com/role: arn:aws:sts::401740808892:assumed-role/wazuh
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: sts-id
                      operator: In
                      values:
                        - '1'
                topologyKey: kubernetes.io/hostname
      volumes:
        - name: config
          configMap:
            name: wazuh-manager-worker-0-conf
      serviceAccountName: 'wazuh'
      containers:
        - name: wazuh-manager
          image: {{ printf "%s/wazuh:%s" .Values.versions.imagesource .Values.versions.wazuh }}
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 1
              memory: 3Gi
          volumeMounts:
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
            - name: pvc-wz
              mountPath: /var/ossec/data
            - name: pvc-wz
              mountPath: /etc/postfix
          ports:
            - containerPort: 1514
              name: agents-events
            - containerPort: 1516
              name: cluster
          securityContext:
            privileged: true
  volumeClaimTemplates:
    - metadata:
        name: pvc-wz
        namespace: wazuh
      spec:
        accessModes:
          - {{ .Values.disk.accessmode }} #ReadWriteMany #Once
        storageClassName:  {{.Values.disk.storageclass }} #azurefile #gp2-encrypted-retained
        resources:
          requests:
            storage: {{ .Values.wazuhworker.data.size }}
